# Generated by Django 4.0.4 on 2022-05-20 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='providers.address'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='social_role',
            field=models.TextField(blank=True, null=True),
        ),
    ]
